Using TensorFlow backend.
2018-09-28 09:21:00.690720: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
2018-09-28 09:21:00.696012: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
2018-09-28 09:21:09.994620: E tensorflow/core/framework/tensor.cc:118] Input size was 4 and expected 1
2018-09-28 09:21:09.994707: E tensorflow/core/framework/tensor.cc:118] Input size was 4 and expected 1
2018-09-28 09:21:09.994743: E tensorflow/core/framework/tensor.cc:118] Input size was 4 and expected 1
2018-09-28 09:21:10.043510: E tensorflow/core/framework/tensor.cc:118] Input size was 4 and expected 1
2018-09-28 09:21:10.054535: E tensorflow/core/framework/tensor.cc:118] Input size was 4 and expected 1
2018-09-28 09:21:10.065512: E tensorflow/core/framework/tensor.cc:118] Input size was 4 and expected 1
2018-09-28 09:21:10.859033: E tensorflow/core/framework/tensor.cc:118] Input size was 4 and expected 1
2018-09-28 09:21:10.869207: E tensorflow/core/framework/tensor.cc:118] Input size was 4 and expected 1
2018-09-28 09:21:10.879339: E tensorflow/core/framework/tensor.cc:118] Input size was 4 and expected 1
2018-09-28 09:21:11.139054: E tensorflow/core/framework/tensor.cc:118] Input size was 4 and expected 1
2018-09-28 09:21:11.139104: E tensorflow/core/framework/tensor.cc:118] Input size was 4 and expected 1
2018-09-28 09:21:11.139139: E tensorflow/core/framework/tensor.cc:118] Input size was 4 and expected 1
2018-09-28 09:21:11.348009: E tensorflow/core/framework/tensor.cc:118] Input size was 4 and expected 1
2018-09-28 09:21:11.348062: W tensorflow/core/framework/op_kernel.cc:1252] OP_REQUIRES failed at constant_op.cc:75 : Invalid argument: Cannot parse tensor from tensor_proto.
2018-09-28 09:21:11.348077: E tensorflow/core/framework/tensor.cc:118] Input size was 4 and expected 1
2018-09-28 09:21:11.348097: E tensorflow/core/common_runtime/executor.cc:697] Executor failed to create kernel. Invalid argument: Cannot parse tensor from tensor_proto.
	 [[Node: DMT/_192 = Const[dtype=DT_UINT8, value=<Invalid TensorProto: dtype: DT_UINT8 tensor_shape { dim { size: 1 } } tensor_content: "\000\000\000\000">, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
2018-09-28 09:21:11.375891: E tensorflow/core/framework/tensor.cc:118] Input size was 4 and expected 1
2018-09-28 09:21:11.375915: W tensorflow/core/framework/op_kernel.cc:1252] OP_REQUIRES failed at constant_op.cc:75 : Invalid argument: Cannot parse tensor from tensor_proto.
2018-09-28 09:21:11.375926: E tensorflow/core/framework/tensor.cc:118] Input size was 4 and expected 1
2018-09-28 09:21:11.375941: E tensorflow/core/common_runtime/executor.cc:697] Executor failed to create kernel. Invalid argument: Cannot parse tensor from tensor_proto.
	 [[Node: DMT/_192 = Const[dtype=DT_UINT8, value=<Invalid TensorProto: dtype: DT_UINT8 tensor_shape { dim { size: 1 } } tensor_content: "\000\000\000\000">, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
2018-09-28 09:21:11.426139: E tensorflow/core/framework/tensor.cc:118] Input size was 4 and expected 1
2018-09-28 09:21:11.426207: W tensorflow/core/framework/op_kernel.cc:1252] OP_REQUIRES failed at constant_op.cc:75 : Invalid argument: Cannot parse tensor from proto: dtype: DT_UINT8
tensor_shape {
  dim {
    size: 1
  }
}
tensor_content: "\000\000\000\000"

2018-09-28 09:21:11.426224: E tensorflow/core/framework/tensor.cc:118] Input size was 4 and expected 1
2018-09-28 09:21:11.426238: E tensorflow/core/common_runtime/executor.cc:697] Executor failed to create kernel. Invalid argument: Cannot parse tensor from proto: dtype: DT_UINT8
tensor_shape {
  dim {
    size: 1
  }
}
tensor_content: "\000\000\000\000"

	 [[Node: DMT/_192 = Const[dtype=DT_UINT8, value=<Invalid TensorProto: dtype: DT_UINT8 tensor_shape { dim { size: 1 } } tensor_content: "\000\000\000\000">, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Exception tensorflow.python.framework.errors_impl.InvalidArgumentError: InvalidArgumentError() in <bound method _Callable.__del__ of <tensorflow.python.client.session._Callable object at 0x7fc799a63610>> ignored
Epoch 1/2
